#ifndef CONSTANTS_H_INCLUDED
#define CONSTANTS_H_INCLUDED

#include "includes.h"

#define SCREEN_X 1080
#define SCREEN_Y 1080

#define NEURONS_AMOUNT 70
#define NEURONS_CONNECTIONS 200

#define NEURON_MOVE_X 0
#define NEURON_MOVE_Y 1
#define NEURON_MOVE_ANGLE 2
#define NEURON_ATTACK 3
#define NEURON_EAT 4
#define NEURON_SPLIT 5
#define NEURON_ALIVE_1 6
#define NEURON_ALIVE_2 7
#define NEURON_FIELD_ANGLE_R 10
#define NEURON_FIELD_DISTANCE 11
#define NEURON_SEE 12
#define NEURON_SEE_ANGLE 13
#define NEURON_SEE_HEALTH 14
#define NEURON_SEE_GRAVITY 15
#define NEURON_SEE_DISTANCE_1 16
#define NEURON_SEE_DISTANCE_2 17
#define NEURON_SENSE_GRAVITY 18
#define NEURON_SENSE_GRAVITY_ANGLE 19
#define NEURON_SENSE_ANGLE 20
#define NEURON_SENSE_HEALTH 21
#define NEURON_IN_1 22
#define NEURON_IN_2 23
#define NEURON_IN_3 24
#define NEURON_OUT_1 25
#define NEURON_OUT_2 26
#define NEURON_OUT_3 27
#define NEURON_SPEAK_1 28
#define NEURON_SPEAK_2 29
#define NEURON_SPEAK_3 30
#define NEURON_HEAR_1 31
#define NEURON_HEAR_2 32
#define NEURON_HEAR_3 33
#define NEURON_SINE_1 34
#define NEURON_SINE_2 35
#define NEURON_SINE_3 36
#define NEURON_SEE_R 37
#define NEURON_SEE_G 38
#define NEURON_SEE_B 39
#define NEURON_SEE_ANGLE2 40
#define NEURON_SPEEDBOOST 41
#define NEURON_SCHIELD 42
#define NEURON_SEE_AL 43
#define NEURON_SEE_AR 44
#define NEURON_SET1 45
#define NEURON_SET1_ON 46
#define NEURON_SET1_OFF 47
#define NEURON_SET2 45
#define NEURON_SET2_ON 46
#define NEURON_SET2_OFF 47
#define NEURON_SEE_AB 48
#define NEURON_SEE_ALL 49
#define NEURON_SEE_ARR 50
#define NEURON_SEE_ALLL 51
#define NEURON_SEE_ARRR 52
#define NEURON_SEE_TIME 53
#define NEURON_STOP 54


#define NEURONS_START_POTENTIAL 0.0
#define POTENTIALSHIFT 0.5
#define NEURON_MUTATIONRATE 6

#define NEURONS_WEIGHT_SIZE 10
#define NEURONS_WEIGHT_SCALE 30
#define NEURONS_WEIGHT_MULTIPLIER 10

#define AGENT_START_CONNECTIONS 20

#define UNIVERSE_SIZE 5000.0
#define UNIVERSE_COLISSION_MULTIPLYER 0.4
#define UNIVERSE_FORCE 5000000000.0
#define UNIVERSE_FORCE2 10000000000.0
#define UNIVERSE_FRICTION 0.01

#define UNIVERSE_MAX_AGENTS 1000
#define UNIVERSE_START_AGENTS 120

#define AGENT_SIZE 10.0
#define AGENT_SIZE_SCALE 0.0

#define AGENT_TIME 300

#define AGENT_FOV M_PI/4.0
#define AGENT_VISUAL_RANGE AGENT_SIZE *15

#define AGENT_SPEED 0.3
#define AGENT_MAX_SPEED 1.0

#define AGENT_MAX_HEALTH 1000
#define AGENT_SPLIT_HEALTH 500

#define AGENT_EAT_DAMAGE AGENT_MAX_HEALTH / 5.0
#define AGENT_EAT_PERCENTAGE 1.0

#define AGENT_STAMINA 1000

#define SPEEDBOOST 100
#define SPEEDBOOSTCOST AGENT_STAMINA / 3

#define SCHIELD 10
#define SCHIELDCOST AGENT_STAMINA / 3


#endif // CONSTANTS_H_INCLUDED
